// "use client";
import Header from "@/components/layout/Header";
// import "../components/fonts/rght_grotesk/right_go.ttf";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Samuel Ogbonna",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} scroll-smooth transition duration-700`}
      >
        <Header />

        {children}

        <Footer />
      </body>
    </html>
  );
}
